# Generated by Django 4.1.2 on 2022-11-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_correo_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Registro',
        ),
    ]
