# Generated by Django 4.1.2 on 2022-12-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_carreras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carreras',
        ),
    ]
