# Generated by Django 4.1.2 on 2022-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_delete_carreras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterField(
            model_name='registro',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
