# Generated by Django 4.1.2 on 2023-01-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_alter_registro_options_alter_registro_correo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name_plural': 'Registro Mensajes'},
        ),
        migrations.AlterField(
            model_name='registro',
            name='mensaje',
            field=models.TextField(verbose_name='asunto'),
        ),
    ]
