# Generated by Django 4.1.2 on 2022-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacante',
            options={'verbose_name': 'Vacantes y bolsa de trabajo', 'verbose_name_plural': 'vacantes'},
        ),
    ]
