# Generated by Django 4.1.2 on 2022-12-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_alter_vacante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacante',
            options={'verbose_name': 'Vacantes', 'verbose_name_plural': 'vacantes y bolsa de trabajo'},
        ),
    ]
