# Generated by Django 4.1.2 on 2023-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('generacion', models.CharField(max_length=9)),
                ('telefono', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to='curriculum')),
                ('carrera', models.CharField(choices=[('IGE', 'Ing. Gestión Empresarial'), ('CP', 'Contador Público'), ('ISC', 'Ing. Sistemas Computacionales'), ('IM', 'Ing. Mecatrónica'), ('II', 'Ing. Industrial'), ('IE', 'Ing. Electrónica')], default='IGE', max_length=32)),
                ('posgrado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=2, verbose_name='¿Estudia o cuenta con un posgrado?')),
                ('tipo_posgrado', models.CharField(blank=True, max_length=80)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
